name: Run YAPF
on: [push, pull_request]
jobs:
  yapf:
    name: YAPF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements-dev.txt
      - run: yapf -r -d .
